# Generated by Django 4.2 on 2023-04-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="userData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default=0, max_length=255)),
                ("first_name", models.CharField(default=0, max_length=255)),
                ("last_name", models.CharField(default=0, max_length=255)),
                ("phone", models.CharField(default=0, max_length=255)),
                ("upiid", models.CharField(default=0, max_length=255)),
                (
                    "phone_verification_status",
                    models.CharField(default=False, max_length=255),
                ),
            ],
        ),
    ]
